plugins {
    id 'java'
    id "org.sonarqube" version "6.2.0.5505"
}

sonar {
  properties {
    property "sonar.projectKey", "antoine-vinot-sonarsource_scanning"
    property "sonar.organization", "antoine-vinot-sonarsource"
    property "sonar.scanner.sonarcloudUrl", "https://dev17.sc-dev17.io"
    property "sonar.scanner.apiBaseUrl", "https://api.sc-dev17.io"
    property "sonar.token", "f27d3fca39be2dc8fe34f5375c40f256f13241e5"
  }
}

java {
    sourceCompatibility = '21'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    implementation 'org.springframework:spring-web:4.3.11.RELEASE'
}

test {
    useJUnitPlatform()
}
